// Single narrative state vocabulary shared by the forest and the return drive.
export const POST_IMPACT = Object.freeze(Object.fromEntries([
  'HOSPITAL_PHONE_INTRO', 'HOSPITAL_GAMEPLAY', 'PARK_BEFORE_POLICE', 'INVESTIGATE_POLICE',
  'CHECK_OFFICER', 'CHECK_BACKSEAT', 'USE_POLICE_RADIO', 'TAKE_HANDGUN', 'FIRST_ENCOUNTER',
  'FIRST_COMBAT', 'RETURN_TO_CAR', 'CAR_DISABLED', 'SPOT_HOUSE', 'WALK_TO_HOUSE', 'TITLE_REVEAL',
  'IMPACT_OCCURRED', 'INVESTIGATE_ROAD', 'FOLLOW_BLOOD', 'FOREST_FIRST_PERSON', 'FOUND_WOMAN',
  'HELPING_WOMAN', 'WOMAN_IN_CAR', 'DRIVING_WITH_WOMAN', 'WOMAN_AGITATED', 'POLICE_APPROACH', 'PULL_OVER', 'STOPPED',
  'POLICE_PULL_OVER', 'OFFICER_APPROACH', 'BREATHALYZER_TEST', 'OFFICER_ESCORT_OFFER', 'TRANSFER_WOMAN',
  'FOLLOW_POLICE', 'POLICE_CAR_UNSTABLE', 'POLICE_CRASH', 'PARK_AFTER_CRASH', 'INVESTIGATE_POLICE_CAR',
].map(name => [name, name])));
